name: Basic Shell command
on: [push]
jobs:
  Shell-Command:
    runs-on: ubuntu-latest
    steps:
      - name: Run single command
        run: echo "Hello World"
      - name: Run a multi-line script
        run: |
           node -v
           npm -v
  Window-Command:
    runs-on: window-latest
    steps:
        - name: Directory Powershell
          run: Get-Location
        - name: Directory Bash
          run: pwd
          shell: bash

      
