name: Basic Shell command
on: [push]
jobs:
  Shell-Command:
    runs-on: ubuntu-latest
    steps:
      - name: Run single command
        run: echo "Hello World"
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      
